<a href="https://colab.research.google.com/github/Jovankavania/ets-ml-logisticnetwork/blob/main/fetch_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fetch Data Latitude Longitude

In [ ]:
import requests
import pandas as pd
import time
import os

API_KEY = ""
URL = "https://places.googleapis.com/v1/places:searchText"

headers = {
    "Content-Type": "application/json",
    "X-Goog-Api-Key": API_KEY,
    "X-Goog-FieldMask": ",".join([
        "places.displayName",
        "places.location",
        "places.formattedAddress",
        "places.addressComponents",
        "places.id"
    ])
}

list_puskesmas = [
    # ============================================================
    # FAKULTAS / INSTANSI PUSAT & IFK
    # ============================================================
    {
        "nama": "Dinas Kesehatan Kota Surabaya",
        "alamat": "Jalan Raya Jemursari No.197, Sidosermo, Surabaya"
    },
    # PUSKESMAS SURABAYA
    {
        "nama": "Puskesmas dr. Soetomo",
        "alamat": "Grudo 5 No.2, DR. Soetomo, Surabaya"
    },
    {
        "nama": "Puskesmas Gundih",
        "alamat": "Jalan Margodadi No. 36-38, Gundih, Surabaya"
    },
    {
        "nama": "Puskesmas Kedungdoro",
        "alamat": "Jalan Kaliasin Pompa No.79-81, Kedungdoro, Surabaya"
    },
    {
        "nama": "Puskesmas Ketabang",
        "alamat": "Jalan Jaksa Agung Suprapto No.8, Ketabang, Surabaya"
    },
    {
        "nama": "Puskesmas Peneleh",
        "alamat": "Jalan Makam Peneleh No.35, Peneleh, Surabaya"
    },
    {
        "nama": "Puskesmas Simolawang",
        "alamat": "Jl. Simolawang II Bar. No.45 A, Simolawang, Surabaya"
    },
    {
        "nama": "Puskesmas Tambakrejo",
        "alamat": "Jalan Ngaglik No.87, Tambakrejo, Surabaya"
    },
    {
        "nama": "Puskesmas Tembok Dukuh",
        "alamat": "Jalan Kalibutuh No.26, Tembok Dukuh, Surabaya"
    },

    {
        "nama": "Puskesmas Asemrowo",
        "alamat": "Jalan Asem Raya No.10, Asem Rowo, Surabaya"
    },
    {
        "nama": "Puskesmas Balongsari",
        "alamat": "Jalan Balongsari Tama Selatan No.2, Balongsari, Surabaya"
    },
    {
        "nama": "Puskesmas Bangkingan",
        "alamat": "Jalan Raya Bangkingan, Bangkingan, Surabaya"
    },
    {
        "nama": "Puskesmas Benowo",
        "alamat": "Jalan Raya Benowo, Benowo, Surabaya"
    },
    {
        "nama": "Puskesmas Jeruk",
        "alamat": "Jalan Raya Menganti Jeruk 277 A, Surabaya"
    },
    {
        "nama": "Puskesmas Lidah Kulon",
        "alamat": "Jalan Menganti Lidah Kulon No.5, Lidah Kulon, Surabaya"
    },
    {
        "nama": "Puskesmas Lontar",
        "alamat": "Jalan Raya Lontar No.26, Lontar, Surabaya"
    },
    {
        "nama": "Puskesmas Made",
        "alamat": "Jalan Raya Made No.116, Made, Surabaya"
    },
    {
        "nama": "Puskesmas Manukan Kulon",
        "alamat": "Jalan Manukan Dalam No.12, Manukan Kulon, Surabaya"
    },
    {
        "nama": "Puskesmas Sememi",
        "alamat": "Jalan Kendung, Sememi, Surabaya"
    },
    {
        "nama": "Puskesmas Simomulyo",
        "alamat": "Jalan Gumuk Bogo No.1, Simomulyo, Surabaya"
    },
    {
        "nama": "Puskesmas Tanjungsari",
        "alamat": "Jalan Raya Tandes Lor No.116, Tanjungsari, Surabaya"
    },

    {
        "nama": "Puskesmas Gading",
        "alamat": "Jalan Kapas Lor I F, Gading, Surabaya"
    },
    {
        "nama": "Puskesmas Gunung Anyar",
        "alamat": "Jalan Gunung Anyar Timur No. 70, Gunung Anyar, Surabaya"
    },
    {
        "nama": "Puskesmas Kalijudan",
        "alamat": "Jalan Kalijudan No. 123, Kalijudan, Surabaya"
    },
    {
        "nama": "Puskesmas Kalirungkut",
        "alamat": "Jalan Rungkut Puskesmas No.1, Kali Rungkut, Surabaya"
    },
    {
        "nama": "Puskesmas Keputih",
        "alamat": "Jalan Keputih Tegal No. 19, Keputih, Surabaya"
    },
    {
        "nama": "Puskesmas Klampis Ngasem",
        "alamat": "Jalan Arief Rahman Hakim No. 99 B, Klampis Ngasem, Surabaya"
    },
    {
        "nama": "Puskesmas Medokan Ayu",
        "alamat": "Jalan Medokan Asri Utara IV No. 31, Medokan Ayu, Surabaya"
    },
    {
        "nama": "Puskesmas Menur",
        "alamat": "Jalan Manyar Rejo I No. 35, Menur Pumpungan, Surabaya"
    },
    {
        "nama": "Puskesmas Mojo",
        "alamat": "Jalan Mojo Klanggru Wetan II No. 11, Mojo, Surabaya"
    },
    {
        "nama": "Puskesmas Mulyorejo",
        "alamat": "Jalan Mulyorejo Utara No. 201, Mulyorejo, Surabaya"
    },
    {
        "nama": "Puskesmas Pacarkeling",
        "alamat": "Jalan Jolotundo Baru III No. 16, Pacar Keling, Surabaya"
    },
    {
        "nama": "Puskesmas Pucangsewu",
        "alamat": "Jalan Pucang Anom Timur No. 72, Pucang Sewu, Surabaya"
    },
    {
        "nama": "Puskesmas Rangkah",
        "alamat": "Jalan Rangkah VII No. 94, Rangkah, Surabaya"
    },
    {
        "nama": "Puskesmas Tenggilis",
        "alamat": "Jalan Rungkut Mejoyo Selatan IV No. 1A, Kali Rungkut, Surabaya"
    },

    {
        "nama": "Puskesmas Bulak Banteng",
        "alamat": "Jalan Dukuh Lebar Gg. Perintis Utama, Bulak Banteng, Surabaya"
    },
    {
        "nama": "Puskesmas Dupak",
        "alamat": "Jalan Dupak Bangunrejo Gang Poliklinik No. 6, Dupak, Surabaya"
    },
    {
        "nama": "Puskesmas Kenjeran",
        "alamat": "Jalan Tambak Deres No. 2, Kenjeran, Surabaya"
    },
    {
        "nama": "Puskesmas Krembangan Selatan",
        "alamat": "Jalan Pesapen Selatan No. 70, Krembangan Selatan, Surabaya"
    },
    {
        "nama": "Puskesmas Moro Krembangan",
        "alamat": "Jalan Tambak Asri Gg. XIII No. 7, Morokrembangan, Surabaya"
    },
    {
        "nama": "Puskesmas Pegirian",
        "alamat": "Jalan Karang Tembok No. 39, Pegirian, Surabaya"
    },
    {
        "nama": "Puskesmas Perak Timur",
        "alamat": "Jalan Perak Barat No. 29, Perak Barat, Surabaya"
    },
    {
        "nama": "Puskesmas Sawah Pulo",
        "alamat": "Jalan Sawah Pulo Kulon No. 2, Ujung, Surabaya"
    },
    {
        "nama": "Puskesmas Sidotopo",
        "alamat": "Jalan Pegirian No. 236, Sidotopo, Surabaya"
    },
    {
        "nama": "Puskesmas Sidotopo Wetan",
        "alamat": "Jalan Randu No. 38, Sidotopo Wetan, Surabaya"
    },
    {
        "nama": "Puskesmas Tambak Wedi",
        "alamat": "Jalan Tambak Wedi, Surabaya"
    },
    {
        "nama": "Puskesmas Tanah Kali Kedinding",
        "alamat": "Jalan HM Noer No. 226, Tanah Kali Kedinding, Surabaya"
    },
    {
        "nama": "Puskesmas Wonokusumo",
        "alamat": "Jalan Wonokusumo Tengah No. 55, Wonokusumo, Surabaya"
    },

    {
        "nama": "Puskesmas Balas Klumprik",
        "alamat": "Jalan Balas Klumprik, Balas Klumprik, Surabaya"
    },
    {
        "nama": "Puskesmas Banyu Urip",
        "alamat": "Jalan Banyu Urip Kidul VI No.8, Banyu Urip, Surabaya"
    },
    {
        "nama": "Puskesmas Dukuh Kupang",
        "alamat": "Jalan Dukuh Kupang XXV No.48, Dukuh Kupang, Surabaya"
    },
    {
        "nama": "Puskesmas Gayungan",
        "alamat": "Jalan Gayungsari Barat No.124, Gayungan, Surabaya"
    },
    {
        "nama": "Puskesmas Jagir",
        "alamat": "Jalan Bendul Merisi No.1, Jagir, Surabaya"
    },
    {
        "nama": "Puskesmas Jemursari",
        "alamat": "Jalan Jemursari Selatan IV No. 5, Jemur Wonosari, Surabaya"
    },
    {
        "nama": "Puskesmas Kebonsari",
        "alamat": "Jalan Kebonsari Manunggal, Kebonsari, Surabaya"
    },
    {
        "nama": "Puskesmas Kedurus",
        "alamat": "Jalan Raya Kedurus No. 46, Kedurus, Surabaya"
    },
    {
        "nama": "Puskesmas Ngagel Rejo",
        "alamat": "Jalan Ngagel Dadi III No.17, Ngagelrejo, Surabaya"
    },
    {
        "nama": "Puskesmas Pakis",
        "alamat": "Jalan Kembang Kuning Makam No. 6, Pakis, Surabaya"
    },
    {
        "nama": "Puskesmas Putat Jaya",
        "alamat": "Jalan Kupang Gn. Timur Gg. V, Putat Jaya, Surabaya"
    },
    {
        "nama": "Puskesmas Sawahan",
        "alamat": "Jalan Arjuno No.119, Sawahan, Surabaya"
    },
    {
        "nama": "Puskesmas Sidosermo",
        "alamat": "Jalan Sidosermo Gg. Damri No. 51, Jagir, Surabaya"
    },
    {
        "nama": "Puskesmas Siwalankerto",
        "alamat": "Jalan Siwalankerto No. 134, Siwalankerto, Surabaya"
    },
    {
        "nama": "Puskesmas Wiyung",
        "alamat": "Jalan Raya Menganti Gg. Ps. No. 1, Wiyung, Surabaya"
    },
    {
        "nama": "Puskesmas Wonokromo",
        "alamat": "Jalan Karangrejo VI No.4, Wonokromo, Surabaya"
    }
]


# ============================================================
# 3. NAMA FILE OUTPUT
# ============================================================

filename = "/content/drive/MyDrive/puskesmas-rute/puskesmas_surabaya_barat.csv"


# ============================================================
# 4. CEK DATA YANG SUDAH PERNAH DISIMPAN
# ============================================================

sudah_terambil = []

if os.path.exists(filename):

    df_lama = pd.read_csv(filename)

    if "Input Nama" in df_lama.columns:
        sudah_terambil = (
            df_lama["Input Nama"]
            .dropna()
            .tolist()
        )

        print(
            f"ℹ️ File '{filename}' ditemukan. "
            f"{len(sudah_terambil)} data akan di-SKIP."
        )


# ============================================================
# 5. PROSES FETCHING
# ============================================================

total = len(list_puskesmas)

print("=" * 60)
print(f"FETCHING {total} PUSKESMAS SURABAYA BARAT")
print("=" * 60)


for idx, puskesmas in enumerate(list_puskesmas, 1):

    nama = puskesmas["nama"]
    alamat = puskesmas["alamat"]

    # --------------------------------------------------------
    # SKIP kalau sudah pernah berhasil disimpan
    # --------------------------------------------------------

    if nama in sudah_terambil:

        print(
            f"[{idx}/{total}] ⏩ SKIP: "
            f"{nama} (sudah tersimpan)"
        )

        continue


    # --------------------------------------------------------
    # QUERY GOOGLE
    # --------------------------------------------------------

    query_spesifik = f"{nama}, {alamat}"

    payload = {
        "textQuery": query_spesifik,
        "languageCode": "id",
        "pageSize": 1
    }


    # --------------------------------------------------------
    # RETRY SETTING
    # --------------------------------------------------------

    max_retries = 5
    delay = 3

    success = False


    # ========================================================
    # RETRY LOOP
    # ========================================================

    for attempt in range(max_retries):

        try:

            response = requests.post(
                URL,
                json=payload,
                headers=headers
            )


            # =================================================
            # RESPONSE BERHASIL
            # =================================================

            if response.status_code == 200:

                data = response.json()

                places = data.get("places", [])


                # ------------------------------------------------
                # GOOGLE MENEMUKAN TEMPAT
                # ------------------------------------------------

                if places:

                    p = places[0]


                    # ============================================
                    # KOORDINAT
                    # ============================================

                    location = p.get(
                        "location",
                        {}
                    )

                    latitude = location.get(
                        "latitude"
                    )

                    longitude = location.get(
                        "longitude"
                    )


                    # ============================================
                    # ADDRESS
                    # ============================================

                    components = p.get(
                        "addressComponents",
                        []
                    )

                    kota = None
                    kecamatan = None


                    for comp in components:

                        types = comp.get(
                            "types",
                            []
                        )

                        if "administrative_area_level_2" in types:

                            kota = comp.get(
                                "longText"
                            )

                        if "administrative_area_level_3" in types:

                            kecamatan = comp.get(
                                "longText"
                            )


                    # ============================================
                    # DATA YANG DISIMPAN
                    # ============================================

                    row_data = {

                        "Input Nama": nama,

                        "Input Alamat": alamat,

                        "Nama di Google Maps":
                            p.get(
                                "displayName",
                                {}
                            ).get(
                                "text"
                            ),

                        "Latitude":
                            latitude,

                        "Longitude":
                            longitude,

                        "Kota/Kabupaten":
                            kota,

                        "Kecamatan":
                            kecamatan,

                        "Alamat Google Maps":
                            p.get(
                                "formattedAddress"
                            ),

                        "Google Place ID":
                            p.get(
                                "id"
                            )
                    }


                    # ============================================
                    # SAVE LANGSUNG KE CSV
                    # ============================================

                    df_single = pd.DataFrame(
                        [row_data]
                    )
                    header_status = not os.path.exists(
                        filename
                    )
                    df_single.to_csv(
                        filename,
                        mode="a",
                        index=False,
                        header=header_status
                    )


                    print(
                        f"[{idx}/{total}] ✅ OK: "
                        f"{nama} "
                        f"→ ({latitude}, {longitude})"
                    )


                    success = True


                # ------------------------------------------------
                # TIDAK DITEMUKAN
                # ------------------------------------------------

                else:

                    print(
                        f"[{idx}/{total}] ⚠️ KOSONG: "
                        f"{nama} tidak ditemukan."
                    )

                    success = True


                break


            # =================================================
            # RATE LIMIT
            # =================================================

            elif response.status_code == 429:

                print(
                    f"[{idx}/{total}] ⏳ 429 Rate Limit "
                    f"untuk '{nama}'. "
                    f"Menunggu {delay} detik..."
                )

                time.sleep(delay)

                delay *= 2


            # =================================================
            # ERROR LAIN
            # =================================================

            else:

                print(
                    f"[{idx}/{total}] ❌ ERROR "
                    f"[{response.status_code}] "
                    f"{nama}"
                )

                print(
                    response.text[:500]
                )

                break


        # =====================================================
        # EXCEPTION
        # =====================================================

        except Exception as e:
            print(
                f"[{idx}/{total}] 💥 EXCEPTION "
                f"{nama}: {e}"
            )
            break
    # ========================================================
    # JEDA ANTAR REQUEST
    # ========================================================

    time.sleep(3)

# ============================================================
# 6. SELESAI
# ============================================================

print()
print("=" * 60)
print("FETCHING SELESAI")
print("=" * 60)

print(
    f"Data tersimpan di: {filename}"
)

============================================================
FETCHING 64 PUSKESMAS SURABAYA BARAT
============================================================
[1/64] ✅ OK: Dinas Kesehatan Kota Surabaya → (-7.317060400000001, 112.75160389999999)
[2/64] ✅ OK: Puskesmas dr. Soetomo → (-7.2775069000000006, 112.736538)
[3/64] ✅ OK: Puskesmas Gundih → (-7.2472639, 112.7252881)
[4/64] ✅ OK: Puskesmas Kedungdoro → (-7.263557, 112.73823000000002)
[5/64] ✅ OK: Puskesmas Ketabang → (-7.2580795, 112.74678990000001)
[6/64] ✅ OK: Puskesmas Peneleh → (-7.252334299999999, 112.74071119999999)
[7/64] ✅ OK: Puskesmas Simolawang → (-7.234767, 112.751167)
[8/64] ✅ OK: Puskesmas Tambakrejo → (-7.249123999999999, 112.75532299999999)
[9/64] ✅ OK: Puskesmas Tembok Dukuh → (-7.2545546000000005, 112.7191737)
[10/64] ✅ OK: Puskesmas Asemrowo → (-7.251825800000001, 112.7143102)
[11/64] ✅ OK: Puskesmas Balongsari → (-7.259209299999998, 112.67831489999999)
[12/64] ✅ OK: Puskesmas Bangkingan → (-7.3247903999999995, 112.6561878)
[13/64] ✅ OK: Puskesmas Benowo → (-7.234874400000001, 112.6114509)
[14/64] ✅ OK: Puskesmas Jeruk → (-7.3054344, 112.63840359999999)
[15/64] ✅ OK: Puskesmas Lidah Kulon → (-7.306591999999999, 112.661473)
[16/64] ✅ OK: Puskesmas Lontar → (-7.2851859999999995, 112.6628885)
[17/64] ✅ OK: Puskesmas Made → (-7.2773157, 112.6369993)
[18/64] ✅ OK: Puskesmas Manukan Kulon → (-7.2630041, 112.66892229999999)
[19/64] ✅ OK: Puskesmas Sememi → (-7.2484143, 112.6354104)
[20/64] ✅ OK: Puskesmas Simomulyo → (-7.262438700000001, 112.7117684)
[21/64] ✅ OK: Puskesmas Tanjungsari → (-7.2596496, 112.6893504)
[22/64] ✅ OK: Puskesmas Gading → (-7.242472, 112.76407370000001)
[23/64] ✅ OK: Puskesmas Gunung Anyar → (-7.340692299999999, 112.7839255)
[24/64] ✅ OK: Puskesmas Kalijudan → (-7.2572968, 112.77803689999999)
[25/64] ✅ OK: Puskesmas Kalirungkut → (-7.322233400000001, 112.7707489)
[26/64] ✅ OK: Puskesmas Keputih → (-7.294079299999999, 112.8018084)
[27/64] ✅ OK: Puskesmas Klampis Ngasem → (-7.289155, 112.77852299999999)
[28/64] ✅ OK: Puskesmas Medokan Ayu → (-7.324165799999999, 112.7948462)
[29/64] ✅ OK: Puskesmas Menur → (-7.296826899999999, 112.7642602)
[30/64] ✅ OK: Puskesmas Mojo → (-7.270793199999999, 112.7709091)
[31/64] ✅ OK: Puskesmas Mulyorejo → (-7.2606759, 112.7848393)
[32/64] ✅ OK: Puskesmas Pacarkeling → (-7.2574206000000006, 112.76266400000002)
[33/64] ✅ OK: Puskesmas Pucangsewu → (-7.286544, 112.75562350000001)
[34/64] ✅ OK: Puskesmas Rangkah → (-7.246254799999999, 112.767253)
[35/64] ✅ OK: Puskesmas Tenggilis → (-7.322375399999999, 112.7621537)
[36/64] ✅ OK: Puskesmas Bulak Banteng → (-7.217728300000001, 112.7662297)
[37/64] ✅ OK: Puskesmas Dupak → (-7.239318699999999, 112.7172026)
[38/64] ✅ OK: Puskesmas Kenjeran → (-7.241078, 112.79517399999999)
[39/64] ✅ OK: Puskesmas Krembangan Selatan → (-7.2332203999999996, 112.7311943)
[40/64] ✅ OK: Puskesmas Moro Krembangan → (-7.230376699999999, 112.7104495)
[41/64] ✅ OK: Puskesmas Pegirian → (-7.2234897, 112.7495493)
[42/64] ✅ OK: Puskesmas Perak Timur → (-7.2307586, 112.7286433)
[43/64] ✅ OK: Puskesmas Sawah Pulo → (-7.2229407, 112.74458419999999)
[44/64] ✅ OK: Puskesmas Sidotopo → (-7.2303599, 112.7459062)
[45/64] ✅ OK: Puskesmas Sidotopo Wetan → (-7.226458000000001, 112.7633664)
[46/64] ✅ OK: Puskesmas Tambak Wedi → (-7.2171453, 112.7724322)
[47/64] ✅ OK: Puskesmas Tanah Kali Kedinding → (-7.2301649, 112.7745247)
[48/64] ✅ OK: Puskesmas Wonokusumo → (-7.219699, 112.75255299999999)
[49/64] ✅ OK: Puskesmas Balas Klumprik → (-7.3315341, 112.6896922)
[50/64] ✅ OK: Puskesmas Banyu Urip → (-7.271597000000001, 112.71996999999999)
[51/64] ✅ OK: Puskesmas Dukuh Kupang → (-7.2833154, 112.7121566)
[52/64] ✅ OK: Puskesmas Gayungan → (-7.3381002, 112.7187041)
[53/64] ✅ OK: Puskesmas Jagir → (-7.305662999999999, 112.737718)
[54/64] ✅ OK: Puskesmas Jemursari → (-7.326114500000001, 112.7400574)
[55/64] ✅ OK: Puskesmas Kebonsari → (-7.328396499999999, 112.7142399)
[56/64] ✅ OK: Puskesmas Kedurus → (-7.3196769, 112.7096237)
[57/64] ✅ OK: Puskesmas Ngagel Rejo → (-7.2929781, 112.7487578)
[58/64] ✅ OK: Puskesmas Pakis → (-7.281827400000001, 112.7280236)
[59/64] ✅ OK: Puskesmas Putat Jaya → (-7.281467399999999, 112.7223705)
[60/64] ✅ OK: Puskesmas Sawahan → (-7.265593999999999, 112.727664)
[61/64] ✅ OK: Puskesmas Sidosermo → (-7.3072181999999986, 112.7557154)
[62/64] ✅ OK: Puskesmas Siwalankerto → (-7.3402823999999995, 112.736466)
[63/64] ✅ OK: Puskesmas Wiyung → (-7.3149058, 112.69392669999999)
[64/64] ✅ OK: Puskesmas Wonokromo → (-7.3031905, 112.73040359999999)

============================================================
FETCHING SELESAI
============================================================
Data tersimpan di: /content/drive/MyDrive/puskesmas-rute/puskesmas_surabaya_barat.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#FETCH DATA GRAF DAN OSMNX

In [ ]:
!pip install -q osmnx geopandas

import numpy as np
import pandas as pd
import geopandas as gpd
import networkx as nx
import osmnx as ox
import os

from shapely.geometry import box

print("OSMnx version:", ox.__version__)

OSMnx version: 2.1.1

In [ ]:
folder_graph = "/content/drive/MyDrive/puskesmas-rute"

In [ ]:
import os

graph_asli_path = os.path.join(
    folder_graph,
    "surabaya_drive.graphml"
)

graph_routing_path = os.path.join(
    folder_graph,
    "surabaya_routing.graphml"
)

In [ ]:
# ============================================================
# LOAD DATA LOKASI
# ============================================================

filename = "/content/drive/MyDrive/puskesmas-rute/puskesmas_surabaya.csv"

df_lokasi = pd.read_csv(filename)

display(
    df_lokasi[
        [
            "Input Nama",
            "Latitude",
            "Longitude",
            "Kecamatan"
        ]
    ]
)

print("Jumlah lokasi:", len(df_lokasi))

                       Input Nama  Latitude   Longitude            Kecamatan
0   Dinas Kesehatan Kota Surabaya -7.317060  112.751604   Kecamatan Wonocolo
1           Puskesmas dr. Soetomo -7.277507  112.736538  Kecamatan Tegalsari
2                Puskesmas Gundih -7.247264  112.725288    Kecamatan Bubutan
3            Puskesmas Kedungdoro -7.263557  112.738230  Kecamatan Tegalsari
4              Puskesmas Ketabang -7.258080  112.746790    Kecamatan Genteng
..                            ...       ...         ...                  ...
59              Puskesmas Sawahan -7.265594  112.727664    Kecamatan Sawahan
60            Puskesmas Sidosermo -7.307218  112.755715   Kecamatan Wonocolo
61         Puskesmas Siwalankerto -7.340282  112.736466   Kecamatan Wonocolo
62               Puskesmas Wiyung -7.314906  112.693927     Kecamatan Wiyung
63            Puskesmas Wonokromo -7.303191  112.730404  Kecamatan Wonokromo

[64 rows x 4 columns]

Jumlah lokasi: 64

In [ ]:
# ============================================================
# VALIDASI KOORDINAT
# ============================================================

assert df_lokasi["Latitude"].notna().all(), \
    "Masih ada latitude kosong."

assert df_lokasi["Longitude"].notna().all(), \
    "Masih ada longitude kosong."

print("✅ Semua koordinat tersedia")

✅ Semua koordinat tersedia

In [ ]:
# ============================================================
# ATRIBUT OSM
# ============================================================

extra_tags = [
    "surface",
    "smoothness",

    "lanes",
    "maxspeed",

    "width",
    "est_width",

    "service",
    "access",
    "motor_vehicle",

    "junction",
    "bridge",
    "tunnel"
]

ox.settings.useful_tags_way = list(
    dict.fromkeys(
        ox.settings.useful_tags_way + extra_tags
    )
)

ox.settings.use_cache = True

print("Tag yang disimpan:")
print(ox.settings.useful_tags_way)

Tag yang disimpan:
['access', 'area', 'bridge', 'est_width', 'highway', 'junction', 'landuse', 'lanes', 'maxspeed', 'name', 'oneway', 'ref', 'service', 'tunnel', 'width', 'surface', 'smoothness', 'motor_vehicle']

In [ ]:
# ============================================================
# MEMBUAT BOUNDING BOX DARI SELURUH TITIK
# + MARGIN 2 KM
# ============================================================

gdf_lokasi = gpd.GeoDataFrame(
    df_lokasi.copy(),
    geometry=gpd.points_from_xy(
        df_lokasi["Longitude"],
        df_lokasi["Latitude"]
    ),
    crs="EPSG:4326"
)

# Cari sistem koordinat UTM lokal
utm_crs = gdf_lokasi.estimate_utm_crs()

gdf_utm = gdf_lokasi.to_crs(utm_crs)

# Ambil batas titik
minx, miny, maxx, maxy = gdf_utm.total_bounds

# Tambahkan margin 2 km
margin_m = 2000

bbox_utm = box(
    minx - margin_m,
    miny - margin_m,
    maxx + margin_m,
    maxy + margin_m
)

# Balik lagi ke latitude-longitude
bbox_wgs = (
    gpd.GeoSeries(
        [bbox_utm],
        crs=utm_crs
    )
    .to_crs("EPSG:4326")
    .iloc[0]
)

left, bottom, right, top = bbox_wgs.bounds

bbox = (
    left,
    bottom,
    right,
    top
)

print("Bounding box:")
print("West :", left)
print("South:", bottom)
print("East :", right)
print("North:", top)

Bounding box:
West : 112.59321801442952
South: -7.35949232768074
East : 112.8201807237088
North: -7.198877120151078

In [ ]:
# ============================================================
# DEFINISI PATH GRAPH
# ============================================================
graph_path = "/content/drive/MyDrive/puskesmas-rute/surabaya_drive.graphml"

# ============================================================
# CEK APAKAH GRAPH SUDAH TERSEDIA
# ============================================================

if os.path.exists(graph_path):

    print("Ģ Graph ditemukan di Google Drive")
    print("Memuat graph yang sudah disimpan...")

    G = ox.io.load_graphml(
        filepath=graph_path
    )

    print("✅ Graph berhasil dimuat tanpa fetching ulang")

else:

    print("ጁ Graph belum tersedia")
    print("Mengambil jaringan jalan dari OpenStreetMap...")

    G = ox.graph.graph_from_bbox(
        bbox,
        network_type="drive_service",
        simplify=True,
        retain_all=False,
        truncate_by_edge=True
    )

    print("✅ Jaringan jalan berhasil diambil")

    # Tambahkan estimasi kecepatan
    G = ox.routing.add_edge_speeds(G)

    # Tambahkan estimasi waktu perjalanan
    G = ox.routing.add_edge_travel_times(G)

    # Simpan graph ke Google Drive
    ox.io.save_graphml(
        G,
        filepath=graph_path
    )

    print("✅ Graph berhasil disimpan")

# ============================================================
# VALIDASI ATRIBUT SETELAH LOAD
# ============================================================

if not all(
    "speed_kph" in d
    for _, _, _, d in G.edges(keys=True, data=True)
):
    G = ox.routing.add_edge_speeds(G)

if not all(
    "travel_time" in d
    for _, _, _, d in G.edges(keys=True, data=True)
):
    G = ox.routing.add_edge_travel_times(G)

    ox.io.save_graphml(
        G,
        filepath=graph_path
    )

# ============================================================
# INFORMASI GRAPH
# ============================================================

print("\n===== INFORMASI GRAPH =====")

print("Jumlah node:", len(G.nodes))
print("Jumlah edge:", len(G.edges))
print("File graph:", graph_path)
print("Ukuran file (MB):",
      round(os.path.getsize(graph_path) / 1024**2, 2))

Ģ Graph ditemukan di Google Drive
Memuat graph yang sudah disimpan...
✅ Graph berhasil dimuat tanpa fetching ulang

===== INFORMASI GRAPH =====
Jumlah node: 59362
Jumlah edge: 139462
File graph: /content/drive/MyDrive/puskesmas-rute/surabaya_drive.graphml
Ukuran file (MB): 73.31

In [ ]:
# ============================================================
# GRAPH → GEODATAFRAME
# ============================================================

nodes, edges = ox.convert.graph_to_gdfs(G)

print("Jumlah ruas:", len(edges))

kolom = [
    "name",

    "highway",
    "length",

    "speed_kph",
    "travel_time",

    "oneway",

    "service",

    "lanes",
    "maxspeed",

    "width",
    "surface"
]

kolom_tersedia = [
    c
    for c in kolom
    if c in edges.columns
]

display(
    edges[kolom_tersedia].head(30)
)

Jumlah ruas: 139462

                                                    name      highway  \
u         v           key
257690921 5579670363  0                 Jalan Kedungdoro      primary
257690939 6865722830  0               Jalan Genteng Kali    secondary
257690940 1682372817  0               Jalan Genteng Kali    secondary
          1682373086  0              Jalan Simpang Dukuh     tertiary
257690943 420895409   0                  Jalan Kertajaya      primary
          3258931753  0               Jalan Dharmawangsa      primary
257690959 3717793099  0                Jalan Ngagel Jaya      primary
          9090565204  0        Jalan Ngagel Jaya Selatan      primary
257690962 3234360484  0               Jalan Ngagel Madya     tertiary
          3717780338  0        Jalan Ngagel Jaya Selatan      primary
257690965 5541567820  0             Jalan Nginden Semolo    secondary
          12035479856 0            Jalan Nginden Baru VI     tertiary
257690969 1507886300  0            Jalan Nginden Baru VI     tertiary
          1507886305  0            Jalan Nginden Baru VI     tertiary
          257690976   0    Jalan Nginden Intan Timur XVI  residential
257690976 1507886303  0    Jalan Nginden Intan Timur XVI  residential
          1719408786  0                              NaN  residential
          1719408725  0                              NaN  residential
          257690969   0    Jalan Nginden Intan Timur XVI  residential
263695201 9465052702  0                 Jalan Kalisari I     tertiary
          265053122   0                 Jalan Kalisari 3     tertiary
          263695371   0                 Jalan Kalisari 3     tertiary
263695365 420032136   0               Jalan Undaan Wetan    secondary
          1722846934  0                Jalan Kalisari II  residential
263695371 4478222243  0                 Jalan Kalisari 3     tertiary
          6869403872  0                Jalan Kalisari II  residential
          263695201   0                 Jalan Kalisari 3     tertiary
263696242 4478171694  0               Jalan Undaan Wetan    secondary
          3672924296  0                  Jalan Kalianyar      primary
263696244 263696242   0                  Jalan Kalianyar      primary

                               length  speed_kph  travel_time  oneway service  \
u         v           key
257690921 5579670363  0    105.883676  55.111111     6.916595    True     NaN
257690939 6865722830  0     53.333271  44.379699     4.326297    True     NaN
257690940 1682372817  0     79.368436  44.379699     6.438222    True     NaN
          1682373086  0     99.059073  45.870968     7.774256   False     NaN
257690943 420895409   0     14.758075  55.111111     0.964036    True     NaN
          3258931753  0     54.983811  55.111111     3.591684    True     NaN
257690959 3717793099  0     12.879862  55.111111     0.841346    True     NaN
          9090565204  0     56.185854  55.111111     3.670205    True     NaN
257690962 3234360484  0     16.263877  45.870968     1.276406    True     NaN
          3717780338  0      6.938299  55.111111     0.453228    True     NaN
257690965 5541567820  0     36.298560  44.379699     2.944473    True     NaN
          12035479856 0     32.637323  45.870968     2.561410   False     NaN
257690969 1507886300  0     41.314633  45.870968     3.242414   False     NaN
          1507886305  0     43.461669  45.870968     3.410916   False     NaN
          257690976   0    166.423923  21.629921    27.698951   False     NaN
257690976 1507886303  0    110.702280  21.629921    18.424857   False     NaN
          1719408786  0     43.541547  21.629921     7.246886   False     NaN
          1719408725  0     42.484073  21.629921     7.070884   False     NaN
          257690969   0    166.423923  21.629921    27.698951   False     NaN
263695201 9465052702  0     31.438011  45.870968     2.467287   False     NaN
          265053122   0     22.680952  45.870968     1.780024   False     NaN
          263695371   0    153.456473  45.870968    12.043419   False     NaN
263695365 420032136   0    134.588418  44.379699    10.917566    True     NaN
          1722846934  0    126.900565  21.629921    21.120837   False     NaN
263695371 4478222243  0     12.593082  45.870968     0.988318   False     NaN
          6869403872  0     75.152606  21.629921    12.508108   False     NaN
          263695201   0    153.456473  45.870968    12.043419   False     NaN
263696242 4478171694  0     32.331994  44.379699     2.622712    True     NaN
          3672924296  0     34.573189  55.111111     2.258410    True     NaN
263696244 263696242   0     90.560246  55.111111     5.915629    True     NaN

                            lanes maxspeed width        surface
u         v           key
257690921 5579670363  0         2      NaN     4        asphalt
257690939 6865722830  0         3      NaN     4        asphalt
257690940 1682372817  0         3      NaN     4        asphalt
          1682373086  0         2      NaN     4        asphalt
257690943 420895409   0         3      NaN     4        asphalt
          3258931753  0         3      NaN   NaN        asphalt
257690959 3717793099  0         3      NaN     5        asphalt
          9090565204  0       NaN      NaN   NaN            NaN
257690962 3234360484  0         2      NaN     3        asphalt
          3717780338  0       NaN      NaN   NaN            NaN
257690965 5541567820  0         2      NaN     6        asphalt
          12035479856 0         1      NaN     8        asphalt
257690969 1507886300  0         1      NaN     8        asphalt
          1507886305  0         1      NaN     8        asphalt
          257690976   0         1      NaN     6        asphalt
257690976 1507886303  0         1      NaN     6        asphalt
          1719408786  0         1      NaN     6        asphalt
          1719408725  0         1      NaN     6        asphalt
          257690969   0         1      NaN     6        asphalt
263695201 9465052702  0         2      NaN     3        asphalt
          265053122   0         1      NaN     3        asphalt
          263695371   0    [2, 1]      NaN     3        asphalt
263695365 420032136   0         4      NaN     4        asphalt
          1722846934  0         1      NaN     3  paving_stones
263695371 4478222243  0         2      NaN     3        asphalt
          6869403872  0         1      NaN     3  paving_stones
          263695201   0    [2, 1]      NaN     3        asphalt
263696242 4478171694  0         4      NaN     4        asphalt
          3672924296  0         2      NaN     3        asphalt
263696244 263696242   0         2      NaN     3        asphalt

In [ ]:
# ============================================================
# PENGECEKAN MISSING VALUE PADA RUAS JALAN (EDGES)
# ============================================================

kolom_target = ['length', 'speed_kph', 'travel_time', 'highway', 'oneway']

# Memastikan kolom benar-benar ada di dalam DataFrame
kolom_ada = [col for col in kolom_target if col in edges.columns]

# Hitung jumlah missing value
missing_count = edges[kolom_ada].isna().sum()

# Hitung persentase missing value
missing_percentage = (edges[kolom_ada].isna().sum() / len(edges)) * 100

# Gabungkan ke dalam sebuah ringkasan DataFrame
summary_missing = pd.DataFrame({
    'Jumlah Missing': missing_count,
    'Persentase (%)': missing_percentage.round(2)
})

display(summary_missing)

             Jumlah Missing  Persentase (%)
length                    0             0.0
speed_kph                 0             0.0
travel_time               0             0.0
highway                   0             0.0
oneway                    0             0.0

In [ ]:
# ============================================================
# DISTRIBUSI HIGHWAY
# ============================================================

def flatten_highway(value):

    if isinstance(value, list):
        return value

    return [value]


hasil = []

for value in edges["highway"].dropna():

    hasil.extend(
        flatten_highway(value)
    )


highway_counts = (
    pd.Series(hasil)
    .value_counts()
    .reset_index()
)

highway_counts.columns = [
    "highway",
    "jumlah_ruas"
]

display(highway_counts)

           highway  jumlah_ruas
0      residential        82011
1          service        20897
2    living_street        17360
3         tertiary         7439
4        secondary         4995
5          primary         3015
6     unclassified         1928
7            trunk         1441
8   secondary_link          256
9     primary_link          234
10   motorway_link          173
11   tertiary_link          162
12      trunk_link          118
13        motorway           83

In [ ]:
# ============================================================
# PERSENTASE DISTRIBUSI HIGHWAY
# ============================================================

# Hitung total ruas jalan
total_ruas = highway_counts["jumlah_ruas"].sum()

# Hitung persentase
highway_counts["persentase (%)"] = (highway_counts["jumlah_ruas"] / total_ruas) * 100

# Format tampilan persentase agar lebih rapi
highway_counts["persentase (%)"] = highway_counts["persentase (%)"].round(2)

display(highway_counts)
print(f"Total keseluruhan ruas jalan: {total_ruas}")

           highway  jumlah_ruas  persentase (%)
0      residential        82011           58.53
1          service        20897           14.91
2    living_street        17360           12.39
3         tertiary         7439            5.31
4        secondary         4995            3.57
5          primary         3015            2.15
6     unclassified         1928            1.38
7            trunk         1441            1.03
8   secondary_link          256            0.18
9     primary_link          234            0.17
10   motorway_link          173            0.12
11   tertiary_link          162            0.12
12      trunk_link          118            0.08
13        motorway           83            0.06

Total keseluruhan ruas jalan: 140112

In [ ]:
# ============================================================
# CEK ONEWAY
# ============================================================

oneway_counts = (
    edges["oneway"]
    .value_counts(
        dropna=False
    )
    .reset_index()
)

oneway_counts.columns = [
    "oneway",
    "jumlah_ruas"
]

display(oneway_counts)

   oneway  jumlah_ruas
0   False       125008
1    True        14454

In [ ]:
# ============================================================
# DIJKSTRA - MATRIKS JARAK DAN WAKTU
# ============================================================

import numpy as np
import pandas as pd
import networkx as nx
import osmnx as ox
import os

# Data lokasi yang sudah dibaca sebelumnya
df_titik = df_lokasi.copy().reset_index(drop=True)

nama_lokasi = df_titik["Input Nama"].tolist()

In [ ]:
# ============================================================
# 1. SNAP KOORDINAT KE NODE JARINGAN JALAN
# ============================================================

node_terdekat, jarak_snap = ox.distance.nearest_nodes(
    G,
    X=df_titik["Longitude"].to_numpy(),
    Y=df_titik["Latitude"].to_numpy(),
    return_dist=True
)

df_titik["osm_node"] = node_terdekat
df_titik["jarak_snap_m"] = jarak_snap

display(
    df_titik[
        ["Input Nama", "osm_node", "jarak_snap_m"]
    ]
)

print("Jarak snap terjauh:",
      round(df_titik["jarak_snap_m"].max(), 2),
      "meter")

# ============================================================
# 2. DIJKSTRA
# ============================================================

nodes = df_titik["osm_node"].tolist()

n = len(nodes)

matrix_length = np.full((n, n), np.inf)
matrix_time = np.full((n, n), np.inf)

print(f"Menghitung Dijkstra untuk {n} lokasi...")

for i, origin in enumerate(nodes):

    # Jalur dengan jarak terpendek
    jarak = nx.single_source_dijkstra_path_length(
        G,
        source=origin,
        weight="length"
    )

    # Jalur dengan waktu tercepat
    waktu = nx.single_source_dijkstra_path_length(
        G,
        source=origin,
        weight="travel_time"
    )

    for j, destination in enumerate(nodes):

        matrix_length[i, j] = jarak.get(
            destination, np.inf
        )

        matrix_time[i, j] = waktu.get(
            destination, np.inf
        )

    print(f"✅ {i+1}/{n}: {nama_lokasi[i]}")

                       Input Nama    osm_node  jarak_snap_m
0   Dinas Kesehatan Kota Surabaya  9597327381     24.446653
1           Puskesmas dr. Soetomo  4481177442     47.357479
2                Puskesmas Gundih  1687753758     12.072612
3            Puskesmas Kedungdoro  5591898053    148.357418
4              Puskesmas Ketabang  5581738570     28.760747
..                            ...         ...           ...
59              Puskesmas Sawahan  4544436194     23.429496
60            Puskesmas Sidosermo  1719470288     20.555904
61         Puskesmas Siwalankerto  5608705129     39.108820
62               Puskesmas Wiyung  6626961220     64.789542
63            Puskesmas Wonokromo  4494343452     28.324745

[64 rows x 3 columns]

Jarak snap terjauh: 148.36 meter
Menghitung Dijkstra untuk 64 lokasi...
✅ 1/64: Dinas Kesehatan Kota Surabaya
✅ 2/64: Puskesmas dr. Soetomo
✅ 3/64: Puskesmas Gundih
✅ 4/64: Puskesmas Kedungdoro
✅ 5/64: Puskesmas Ketabang
✅ 6/64: Puskesmas Peneleh
✅ 7/64: Puskesmas Simolawang
✅ 8/64: Puskesmas Tambakrejo
✅ 9/64: Puskesmas Tembok Dukuh
✅ 10/64: Puskesmas Asemrowo
✅ 11/64: Puskesmas Balongsari
✅ 12/64: Puskesmas Bangkingan
✅ 13/64: Puskesmas Benowo
✅ 14/64: Puskesmas Jeruk
✅ 15/64: Puskesmas Lidah Kulon
✅ 16/64: Puskesmas Lontar
✅ 17/64: Puskesmas Made
✅ 18/64: Puskesmas Manukan Kulon
✅ 19/64: Puskesmas Sememi
✅ 20/64: Puskesmas Simomulyo
✅ 21/64: Puskesmas Tanjungsari
✅ 22/64: Puskesmas Gading
✅ 23/64: Puskesmas Gunung Anyar
✅ 24/64: Puskesmas Kalijudan
✅ 25/64: Puskesmas Kalirungkut
✅ 26/64: Puskesmas Keputih
✅ 27/64: Puskesmas Klampis Ngasem
✅ 28/64: Puskesmas Medokan Ayu
✅ 29/64: Puskesmas Menur
✅ 30/64: Puskesmas Mojo
✅ 31/64: Puskesmas Mulyorejo
✅ 32/64: Puskesmas Pacarkeling
✅ 33/64: Puskesmas Pucangsewu
✅ 34/64: Puskesmas Rangkah
✅ 35/64: Puskesmas Tenggilis
✅ 36/64: Puskesmas Bulak Banteng
✅ 37/64: Puskesmas Dupak
✅ 38/64: Puskesmas Kenjeran
✅ 39/64: Puskesmas Krembangan Selatan
✅ 40/64: Puskesmas Moro Krembangan
✅ 41/64: Puskesmas Pegirian
✅ 42/64: Puskesmas Perak Timur
✅ 43/64: Puskesmas Sawah Pulo
✅ 44/64: Puskesmas Sidotopo
✅ 45/64: Puskesmas Sidotopo Wetan
✅ 46/64: Puskesmas Tambak Wedi
✅ 47/64: Puskesmas Tanah Kali Kedinding
✅ 48/64: Puskesmas Wonokusumo
✅ 49/64: Puskesmas Balas Klumprik
✅ 50/64: Puskesmas Banyu Urip
✅ 51/64: Puskesmas Dukuh Kupang
✅ 52/64: Puskesmas Gayungan
✅ 53/64: Puskesmas Jagir
✅ 54/64: Puskesmas Jemursari
✅ 55/64: Puskesmas Kebonsari
✅ 56/64: Puskesmas Kedurus
✅ 57/64: Puskesmas Ngagel Rejo
✅ 58/64: Puskesmas Pakis
✅ 59/64: Puskesmas Putat Jaya
✅ 60/64: Puskesmas Sawahan
✅ 61/64: Puskesmas Sidosermo
✅ 62/64: Puskesmas Siwalankerto
✅ 63/64: Puskesmas Wiyung
✅ 64/64: Puskesmas Wonokromo

In [ ]:
# ============================================================
# 1. CEK KOMPONEN JARINGAN JALAN
# ============================================================

komponen = list(nx.strongly_connected_components(G))
komponen_utama = max(komponen, key=len)

print("Jumlah komponen:", len(komponen))
print("Jumlah node awal:", len(G.nodes))
print("Node komponen utama:", len(komponen_utama))

# Ambil jaringan yang bisa dilalui dua arah
G_rute = G.subgraph(komponen_utama).copy()

print("Node graph rute:", len(G_rute.nodes))
print("Edge graph rute:", len(G_rute.edges))

# ============================================================
# 2. CEK NODE TERDEKAT SETIAP PUSKESMAS
# ============================================================

df_titik = df_lokasi.copy().reset_index(drop=True)

df_titik["Latitude"] = pd.to_numeric(df_titik["Latitude"])
df_titik["Longitude"] = pd.to_numeric(df_titik["Longitude"])

if df_titik[["Latitude", "Longitude"]].isna().any().any():
    raise ValueError("Ada koordinat yang kosong.")

if not df_titik["Latitude"].between(-90, 90).all():
    raise ValueError("Ada latitude yang tidak valid.")

if not df_titik["Longitude"].between(-180, 180).all():
    raise ValueError("Ada longitude yang tidak valid.")

if df_titik["Input Nama"].duplicated().any():
    raise ValueError("Ada nama lokasi yang duplikat.")

lon = df_titik["Longitude"].to_numpy()
lat = df_titik["Latitude"].to_numpy()

# Node terdekat dari graph awal
node_awal, jarak_awal = ox.distance.nearest_nodes(
    G,
    X=lon,
    Y=lat,
    return_dist=True
)

# Cari ulang pada jaringan yang saling terhubung
node_rute, jarak_rute = ox.distance.nearest_nodes(
    G_rute,
    X=lon,
    Y=lat,
    return_dist=True
)

df_titik["node_awal"] = node_awal
df_titik["node_rute"] = node_rute
df_titik["jarak_awal_m"] = jarak_awal
df_titik["jarak_snap_m"] = jarak_rute

df_titik["node_berubah"] = (
    df_titik["node_awal"] != df_titik["node_rute"]
)

print("\nLokasi yang mengalami perubahan node:")

display(
    df_titik.loc[
        df_titik["node_berubah"],
        [
            "Input Nama",
            "node_awal",
            "node_rute",
            "jarak_awal_m",
            "jarak_snap_m"
        ]
    ]
)

# ============================================================
# 3. VALIDASI JARAK KE NODE JALAN
# ============================================================

# Batas pemeriksaan sementara, bukan standar resmi
batas_snap = 300

lokasi_jauh = df_titik[
    df_titik["jarak_snap_m"] > batas_snap
]

print("\nJarak snap terjauh:",
      round(df_titik["jarak_snap_m"].max(), 2), "meter")

if not lokasi_jauh.empty:

    print("\nLokasi yang perlu dicek ulang:")

    display(
        lokasi_jauh[
            ["Input Nama", "jarak_snap_m", "node_rute"]
        ]
    )

    raise ValueError(
        "Ada lokasi yang terlalu jauh dari jaringan utama. "
        "Periksa koordinat atau cakupan graph sebelum lanjut."
    )

print("Semua lokasi berada dalam batas jarak snap.")

Jumlah komponen: 559
Jumlah node awal: 59362
Node komponen utama: 58746
Node graph rute: 58746
Edge graph rute: 138749

Lokasi yang mengalami perubahan node:

,Input Nama,node_awal,node_rute,jarak_awal_m,jarak_snap_m
0,Dinas Kesehatan Kota Surabaya,9597327381,7664144277,24.446653,33.464354
20,Puskesmas Tanjungsari,9113616866,6937883797,38.586513,42.687250

Jarak snap terjauh: 148.36 meter
Semua lokasi berada dalam batas jarak snap.

In [ ]:
# ============================================================
# 4. HITUNG MATRIKS DIJKSTRA
# ============================================================

nama_lokasi = df_titik["Input Nama"].tolist()
node_lokasi = df_titik["node_rute"].tolist()

n = len(node_lokasi)

matrix_length = np.full((n, n), np.inf)
matrix_time = np.full((n, n), np.inf)

for i, asal in enumerate(node_lokasi):

    hasil_jarak = nx.single_source_dijkstra_path_length(
        G_rute,
        source=asal,
        weight="length"
    )

    hasil_waktu = nx.single_source_dijkstra_path_length(
        G_rute,
        source=asal,
        weight="travel_time"
    )

    for j, tujuan in enumerate(node_lokasi):

        matrix_length[i, j] = hasil_jarak.get(
            tujuan, np.inf
        )

        matrix_time[i, j] = hasil_waktu.get(
            tujuan, np.inf
        )

    print(f"{i+1}/{n} selesai: {nama_lokasi[i]}")

# ============================================================
# 5. CEK HASIL DIJKSTRA
# ============================================================

cek_jarak = np.isfinite(matrix_length).all()
cek_waktu = np.isfinite(matrix_time).all()

print("\nSemua jarak terhubung:", cek_jarak)
print("Semua waktu terhubung:", cek_waktu)

if not (cek_jarak and cek_waktu):
    raise ValueError("Masih ada pasangan yang tidak terhubung.")

# Cek lokasi yang jatuh pada node yang sama
duplikat_node = df_titik[
    df_titik.duplicated("node_rute", keep=False)
]

if not duplikat_node.empty:
    print("\nAda lokasi berbeda pada node jalan yang sama:")
    display(
        duplikat_node[
            ["Input Nama", "node_rute", "jarak_snap_m"]
        ]
    )

# ============================================================
# 6. BUAT DATAFRAME
# ============================================================

df_length = pd.DataFrame(
    matrix_length,
    index=nama_lokasi,
    columns=nama_lokasi
)

df_time = pd.DataFrame(
    matrix_time,
    index=nama_lokasi,
    columns=nama_lokasi
)

print("\nMatriks jarak (meter):")
display(df_length.iloc[:5, :5])

print("\nMatriks waktu (detik):")
display(df_time.iloc[:5, :5])

# ============================================================
# 7. SIMPAN HASIL KE GOOGLE DRIVE
# ============================================================

os.makedirs(folder_graph, exist_ok=True)

ox.io.save_graphml(
    G_rute,
    filepath=graph_routing_path
)

print("Graph routing berhasil disimpan.")

df_titik.to_csv(
    os.path.join(folder_graph, "lokasi_osm_nodes.csv"),
    index=False
)

df_length.to_csv(
    os.path.join(folder_graph, "matrix_length.csv")
)

df_time.to_csv(
    os.path.join(folder_graph, "matrix_time.csv")
)

np.save(
    os.path.join(folder_graph, "matrix_length.npy"),
    matrix_length
)

np.save(
    os.path.join(folder_graph, "matrix_time.npy"),
    matrix_time
)

print("\nGraph dan matriks berhasil disimpan.")

1/64 selesai: Dinas Kesehatan Kota Surabaya
2/64 selesai: Puskesmas dr. Soetomo
3/64 selesai: Puskesmas Gundih
4/64 selesai: Puskesmas Kedungdoro
5/64 selesai: Puskesmas Ketabang
6/64 selesai: Puskesmas Peneleh
7/64 selesai: Puskesmas Simolawang
8/64 selesai: Puskesmas Tambakrejo
9/64 selesai: Puskesmas Tembok Dukuh
10/64 selesai: Puskesmas Asemrowo
11/64 selesai: Puskesmas Balongsari
12/64 selesai: Puskesmas Bangkingan
13/64 selesai: Puskesmas Benowo
14/64 selesai: Puskesmas Jeruk
15/64 selesai: Puskesmas Lidah Kulon
16/64 selesai: Puskesmas Lontar
17/64 selesai: Puskesmas Made
18/64 selesai: Puskesmas Manukan Kulon
19/64 selesai: Puskesmas Sememi
20/64 selesai: Puskesmas Simomulyo
21/64 selesai: Puskesmas Tanjungsari
22/64 selesai: Puskesmas Gading
23/64 selesai: Puskesmas Gunung Anyar
24/64 selesai: Puskesmas Kalijudan
25/64 selesai: Puskesmas Kalirungkut
26/64 selesai: Puskesmas Keputih
27/64 selesai: Puskesmas Klampis Ngasem
28/64 selesai: Puskesmas Medokan Ayu
29/64 selesai: Puskesmas Menur
30/64 selesai: Puskesmas Mojo
31/64 selesai: Puskesmas Mulyorejo
32/64 selesai: Puskesmas Pacarkeling
33/64 selesai: Puskesmas Pucangsewu
34/64 selesai: Puskesmas Rangkah
35/64 selesai: Puskesmas Tenggilis
36/64 selesai: Puskesmas Bulak Banteng
37/64 selesai: Puskesmas Dupak
38/64 selesai: Puskesmas Kenjeran
39/64 selesai: Puskesmas Krembangan Selatan
40/64 selesai: Puskesmas Moro Krembangan
41/64 selesai: Puskesmas Pegirian
42/64 selesai: Puskesmas Perak Timur
43/64 selesai: Puskesmas Sawah Pulo
44/64 selesai: Puskesmas Sidotopo
45/64 selesai: Puskesmas Sidotopo Wetan
46/64 selesai: Puskesmas Tambak Wedi
47/64 selesai: Puskesmas Tanah Kali Kedinding
48/64 selesai: Puskesmas Wonokusumo
49/64 selesai: Puskesmas Balas Klumprik
50/64 selesai: Puskesmas Banyu Urip
51/64 selesai: Puskesmas Dukuh Kupang
52/64 selesai: Puskesmas Gayungan
53/64 selesai: Puskesmas Jagir
54/64 selesai: Puskesmas Jemursari
55/64 selesai: Puskesmas Kebonsari
56/64 selesai: Puskesmas Kedurus
57/64 selesai: Puskesmas Ngagel Rejo
58/64 selesai: Puskesmas Pakis
59/64 selesai: Puskesmas Putat Jaya
60/64 selesai: Puskesmas Sawahan
61/64 selesai: Puskesmas Sidosermo
62/64 selesai: Puskesmas Siwalankerto
63/64 selesai: Puskesmas Wiyung
64/64 selesai: Puskesmas Wonokromo

Semua jarak terhubung: True
Semua waktu terhubung: True

Matriks jarak (meter):

,Dinas Kesehatan Kota Surabaya,Puskesmas dr. Soetomo,Puskesmas Gundih,Puskesmas Kedungdoro,Puskesmas Ketabang
Dinas Kesehatan Kota Surabaya,0.000000,7201.869319,12257.984274,8739.900035,8956.619570
Puskesmas dr. Soetomo,6590.219324,0.000000,5864.146807,2744.690457,3710.086767
Puskesmas Gundih,11078.590187,5358.425704,0.000000,3896.959099,5189.723432
Puskesmas Kedungdoro,8910.707904,3027.502204,4442.973611,0.000000,4140.698840
Puskesmas Ketabang,8586.059446,3758.851371,4344.287929,4293.136543,0.000000

Matriks waktu (detik):

,Dinas Kesehatan Kota Surabaya,Puskesmas dr. Soetomo,Puskesmas Gundih,Puskesmas Kedungdoro,Puskesmas Ketabang
Dinas Kesehatan Kota Surabaya,0.000000,600.428326,930.398813,757.919455,600.963806
Puskesmas dr. Soetomo,595.432044,0.000000,604.046947,431.175504,374.440852
Puskesmas Gundih,860.735000,567.248136,0.000000,414.648269,467.037160
Puskesmas Kedungdoro,706.408615,412.921752,464.653772,0.000000,382.909219
Puskesmas Ketabang,575.736590,380.209382,396.989082,402.945569,0.000000

Graph routing berhasil disimpan.

Graph dan matriks berhasil disimpan.

In [ ]:
G = ox.io.load_graphml(
    filepath=graph_asli_path
)

In [ ]:
G_rute = ox.io.load_graphml(
    filepath=graph_routing_path
)